### ISSUE TITLE
Configurable DOMAIN_ROOT

### ISSUE THREAD

**Issue by karelvasicek** [nickdnk/gatewayapi-php#5]
Could be the `DOMAIN_ROOT`
1. either dropped and domain made configurable
2. or made `protected` and `static::DOMAIN_ROOT` used

to allow using `gatewayapi.eu` domain?

**Comment by nickdnk** [comment]
Hello

What is the purpose of this domain? Why not `.com`?

**Comment by karelvasicek** [comment]
Thanks for your quick response. From what I understood from my client, `.eu` domain is used for fully EU-restricted services (`.com` uses Google servers, `.eu` uses Hetzner).

**Comment by nickdnk** [comment]
I will consult with GatewayAPI tomorrow and update the library then. It will be a boolean parameter most likely; I don't see a need to expose the domain as a variable. It just opens up the door to misconfigurations.

**Comment by nickdnk** [comment]
Added as bool option to the constructor in 3.3.0: https://github.com/nickdnk/gatewayapi-php/commit/940602bc9ff0d03eee1138f2ebe842d6de03debb.
